services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=todolist'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=root'
    ports:
      - '13306:3306'
